#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# the "app_lucky_number" route name is not important yet
app_user:
    path: /user/display
    controller: App\Controller\UserController::display
